// HelpingFamilesNelson-Angular/frontend/src/app/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../_services/auth.service';
import { NgForm, FormControl, FormBuilder, Validators, FormGroup, FormArray } from '@angular/forms';
import { DateAdapter } from '@angular/material/core';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {
  form = new FormGroup({
    username: new FormControl(''),
    email: new FormControl(''),
    password: new FormControl(''),
    address: new FormControl(''),
    phone: new FormControl(''),
    type: new FormControl(''),
  });
  isSubmit = false;
  isSuccessful = false;
  isSignUpFailed = false;
  errorMessage = '';

  constructor(private authService: AuthService) { }

  ngOnInit(): void {
  }

  onSubmit(data: NgForm): void {
    this.isSubmit = true;
    if (data.valid)
    {
      this.authService.register(data.controls['username'].value, data.controls['email'].value, data.controls['password'].value, data.controls['address'].value, data.controls['phone'].value, data.controls['type'].value).subscribe(
        data => {
          console.log(data);
          this.isSuccessful = true;
          this.isSignUpFailed = false;
        },
        err => {
          this.errorMessage = err.error.message;
          this.isSignUpFailed = true;
        }
      );
      window.scroll(0,0);
    }
    else
    {
      console.log(data.controls['password'].errors);
    }
    
  }
}

<div class="col-md-12">
  <div class="card card-container">
    <img
      id="profile-img"
      src="//ssl.gstatic.com/accounts/ui/avatar_2x.png"
      class="profile-img-card"
    />
    <form
      *ngIf="!isSuccessful"
      #registerForm="ngForm"
      name="form"
      (ngSubmit)="onSubmit(registerForm)"
    >
      <div class="form-group">
        <label class="control-label required" for="username">Username</label>
        <input
          type="text"
          class="form-control"
          name="username"
          ngModel
          required
          minlength="5"
          maxlength="30"
          placeholder="Enter Username..."
          #username="ngModel"
        />
        <div class="alert alert-danger" *ngIf="username.errors?.required && this.isSubmit">
          Username is required
        </div>
        <div class="alert alert-danger" *ngIf="username.errors?.minlength && this.isSubmit">
          Username must be 8 characters
        </div>
      </div>
      <div class="form-group">
        <label class="control-label required" for="email">Email</label>
        <input
          type="email"
          class="form-control"
          name="email"
          ngModel
          required
          email
          maxlength="70"
          placeholder="Enter Email..."
          #email="ngModel"
        />
        <div class="alert alert-danger" *ngIf="email.errors?.required && this.isSubmit">
          Email Is Required
        </div>
        <div class="alert alert-danger" *ngIf="email.errors?.email && this.isSubmit">
          Email does not match a valid format
        </div>
      </div>
      <div class="form-group">
        <label class="control-label required" for="password">Password</label>
        <input
          type="password"
          class="form-control"
          name="password"
          ngModel
          required
          password
          minlength="8"
          maxlength="30"
          placeholder="Enter Password..."
          #password="ngModel"
        />
        <div class="alert alert-danger" *ngIf="password.errors?.required && this.isSubmit">
          Password Is Required
        </div>
        <div class="alert alert-danger" *ngIf="password.errors?.minlength && this.isSubmit">
          Password needs to be at least 8 characters
        </div>
      </div>
      <div class="form-group">
        <label class="control-label required" for="address">Address</label>
        <input
          type="text"
          class="form-control"
          name="address"
          ngModel
          required
          placeholder="Enter Address..."
          #address="ngModel"
        />
        <div class="alert alert-danger" *ngIf="address.errors?.required && this.isSubmit">
          Address Is Required
        </div>
      </div>
      <div class="form-group">
        <label class="control-label required" for="phone">Phone Number</label>
        <input
          type="text"
          class="form-control"
          name="phone"
          ngModel
          required
          placeholder="Enter Phone Number..."
          #phone="ngModel"
        />
        <div class="alert alert-danger" *ngIf="phone.errors?.required && this.isSubmit">
          Phone Number Is Required
        </div>
      </div>
      <div class="d-flex flex-row justify-content-center control-label required">
        <div class="p-2">
            <input 
                type="radio"
                id='charity'
                class="form-control"
                name="type"
                value="charity"
                required
                ngModel
                #type="ngModel"
            >
            <label for="charity"><p>Charity</p></label>
        </div>
        <div class="p-2">
          <input 
              type="radio" 
              id="beneficiary" 
              class="form-control"
              name="type" 
              value="beneficiary"
              required
              ngModel
              #type="ngModel"
              >
          <label for="beneficiary"><p>Beneficiary</p></label>
        </div>
      </div>
      <div class="alert alert-danger" *ngIf="type.errors?.required && this.isSubmit">
        Type Is Required
      </div>
      <div class="form-group">
        <button class="btn btn-primary btn-block">Sign Up</button>
      </div>

      <div class="alert alert-warning" *ngIf="registerForm.submitted && isSignUpFailed">
        SignUp failed!<br />{{ errorMessage }}
      </div>
    </form>

    <div class="alert alert-success" *ngIf="isSuccessful">
      Your registration is successful!
    </div>
  </div>
</div>

// HelpingFamiliesNelson-Vue/frontend/src/components/views/Register.vue
<template>
  <div class="col-md-12">
    <div class="card card-container">
      <img
        id="profile-img"
        src="//ssl.gstatic.com/accounts/ui/avatar_2x.png"
        class="profile-img-card"
      />
      <Form @submit="handleRegister" :validation-schema="schema">
        <div v-if="!successful">
          <div class="form-group">
            <label for="username">Username</label>
            <Field name="username" type="text" class="form-control" />
            <ErrorMessage name="username" class="error-feedback" />
          </div>
          <div class="form-group">
            <label for="email">Email</label>
            <Field name="email" type="email" class="form-control" />
            <ErrorMessage name="email" class="error-feedback" />
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <Field name="password" type="password" class="form-control" />
            <ErrorMessage name="password" class="error-feedback" />
          </div>
          <div class="form-group">
            <label for="phone">Phone Number</label>
            <Field name="phone" type="phone" class="form-control" />
            <ErrorMessage name="phone" class="error-feedback" />
          </div>
          <div class="form-group">
            <label for="address">Address</label>
            <Field name="address" type="text" class="form-control" />
            <ErrorMessage name="address" class="error-feedback" />
          </div>
          <div class="form-group">
            <label for="userType">User Type</label>
          <div class="d-flex flex-row justify-content-center">
            <div class="p-2">
                <Field name="userType" id="Charity" value="Charity" type="radio" class="form-control" />
                <label for="Charity"><p>Charity</p></label>
            </div>
            <div class="p-2">
                <Field name="userType" id="Beneficiary" value="Beneficiary" type="radio" class="form-control" />
                <label for="Beneficiary"><p>Beneficiary</p></label>
            </div>
            </div>
            <ErrorMessage name="userType" class="error-feedback" />
          </div>
          <div class="form-group">
            <button class="btn btn-primary btn-block" :disabled="loading">
              <span
                v-show="loading"
                class="spinner-border spinner-border-sm"
              ></span>
              Sign Up
            </button>
          </div>
        </div>
      </Form>

      <div
        v-if="message"
        class="alert"
        :class="successful ? 'alert-success' : 'alert-danger'"
      >
        {{ message }}
      </div>
    </div>
  </div>
</template>

<script>
import { Form, Field, ErrorMessage } from "vee-validate";
import * as yup from "yup";

export default {
  name: "Register",
  components: {
    Form,
    Field,
    ErrorMessage,
  },
  data() {
    const schema = yup.object().shape({
      username: yup
        .string()
        .required("Username is required!")
        .min(3, "Must be at least 3 characters!")
        .max(20, "Must be maximum 20 characters!"),
      email: yup
        .string()
        .required("Email is required!")
        .email("Email is invalid!")
        .max(50, "Must be maximum 50 characters!"),
      password: yup
        .string()
        .required("Password is required!")
        .min(6, "Must be at least 6 characters!")
        .max(40, "Must be maximum 40 characters!"),
      phone: yup
        .string()
        .required("Phone Number is required!"),
      address: yup
        .string()
        .required("Address is required!"),
      userType: yup
        .string()
        .required("User Type is required!")
    });

    return {
      successful: false,
      loading: false,
      message: "",
      schema,
    };
  },
  computed: {
    loggedIn() {
      return this.$store.state.auth.status.loggedIn;
    },
  },
  mounted() {
    if (this.loggedIn) {
      this.$router.push("/profile");
    }
  },
  methods: {
    handleRegister(user) {
      this.message = "";
      this.successful = false;
      this.loading = true;

      this.$store.dispatch("auth/register", user).then(
        (data) => {
          this.message = data.message;
          this.successful = true;
          this.loading = false;
        },
        (error) => {
          this.message =
            (error.response &&
              error.response.data &&
              error.response.data.message) ||
            error.message ||
            error.toString();
          this.successful = false;
          this.loading = false;
        }
      );
    },
  },
};
</script>

<style scoped>
label {
  display: block;
  margin-top: 10px;
}

.card-container.card {
  max-width: 350px !important;
  padding: 40px 40px;
}

.card {
  background-color: #f7f7f7;
  padding: 20px 25px 30px;
  margin: 0 auto 25px;
  margin-top: 50px;
  -moz-border-radius: 2px;
  -webkit-border-radius: 2px;
  border-radius: 2px;
  -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
  -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
  box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}

.profile-img-card {
  width: 96px;
  height: 96px;
  margin: 0 auto 10px;
  display: block;
  -moz-border-radius: 50%;
  -webkit-border-radius: 50%;
  border-radius: 50%;
}

.error-feedback {
  color: red;
}
</style>
