// HelpingFamiliesNelson-Vue/frontend/src/App.vue
<template>
  <div id="app">
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <a href="/" class="navbar-brand">Helping Families Nelson</a>
      <div class="navbar-nav mr-auto">
        <li class="nav-item">
          <router-link to="/home" class="nav-link">
            <div class="p-2">
              <div class="text-center">
                <font-awesome-icon icon="home" />
              </div>
              <div class="text-center">
                <div>Home<br>Kaainga</div>
              </div>
            </div>
          </router-link>
        </li>
        <li class="nav-item">
          <router-link to="/about" class="nav-link">
            <div class="p-2">
              <div class="text-center">
                <font-awesome-icon icon="question-circle" />
              </div>
              <div class="text-center">
                <div>About<br>Mō</div>
              </div>
            </div>
          </router-link>
        </li>
        <li class="nav-item">
          <router-link to="/contact" class="nav-link">
            <div class="p-2">
              <div class="text-center">
                <font-awesome-icon icon="phone" />
              </div>
              <div class="text-center">
                <div>Contact<br>Whakapaa</div>
              </div>
            </div>
          </router-link>
        </li>
         <li class="nav-item">
          <router-link to="/donate" class="nav-link">
            <div class="p-2">
              <div class="text-center">
                <font-awesome-icon icon="cloud-upload-alt" />
              </div>
              <div class="text-center">
                <div>Donate<br>Takoha</div>
              </div>
            </div>
          </router-link>
        </li>
        <li v-if="showAdminBoard" class="nav-item">
          <router-link to="/admin" class="nav-link">Admin Board</router-link>
        </li>
        <li v-if="showModeratorBoard" class="nav-item">
          <router-link to="/mod" class="nav-link">Moderator Board</router-link>
        </li>
        <li class="nav-item">
          <router-link v-if="currentUser" to="/user" class="nav-link">
          <div class="p-2">
              <div class="text-center">
                <font-awesome-icon icon="users"/>
              </div>
              <div class="text-center">
                <div>User<br>Whakapaa</div>
              </div>
            </div>
            </router-link>
        </li>
      </div>

      <div v-if="!currentUser" class="navbar-nav ml-auto">
        <li class="nav-item">
          <router-link to="/register" class="nav-link">
           <li class="nav-item">
              <div class="p-2">
                <div class="text-center">
                  <font-awesome-icon icon="user-plus" />
                </div>
                <div class="text-center">
                  <div>Sign Up<br>hainatanga</div>
                </div>
              </div>
            </li>
          </router-link>
        </li>
        <li class="nav-item">
          <router-link to="/login" class="nav-link">
          <div class="p-2">
                <div class="text-center">
                  <font-awesome-icon icon="sign-in-alt" />
                </div>
                <div class="text-center">
                  <div>Login<br>Takiuru</div>
                </div>
              </div>
          </router-link>
        </li>
      </div>

      <div v-if="currentUser" class="navbar-nav ml-auto">
        <li class="nav-item">
          <router-link to="/profile" class="nav-link">
            <div class="p-2">
              <div class="text-center">
                <font-awesome-icon icon="user" />
              </div>
              <div class="text-center">
                <div>{{ currentUser.username }} Profile<br>Kōtaha</div>
              </div>
            </div>
          </router-link>
        </li>
        <li class="nav-item">
          <a class="nav-link" @click.prevent="logOut">
            <div class="p-2">
              <div class="text-center">
                <font-awesome-icon icon="sign-out-alt" />
              </div>
              <div class="text-center">
                <div>LogOut<br>Putaara</div>
              </div>
            </div>
          </a>
        </li>
      </div>
    </nav>

    <div class="container">
      <router-view />
    </div>

      <footer-section />

  </div>
</template>

<script>
export default {
  computed: {
    currentUser() {
      return this.$store.state.auth.user;
    },
    showAdminBoard() {
      if (this.currentUser && this.currentUser['roles']) {
        return this.currentUser['roles'].includes('ROLE_ADMIN');
      }

      return false;
    },
    showModeratorBoard() {
      if (this.currentUser && this.currentUser['roles']) {
        return this.currentUser['roles'].includes('ROLE_MODERATOR');
      }

      return false;
    }
  },
  methods: {
    logOut() {
      this.$store.dispatch('auth/logout');
      this.$router.push('/login');
    }
  }
};
</script>

// HelpingFamilesNelson-Angular/frontend/src/app/app.component.ts
import { Component, ChangeDetectionStrategy, OnInit } from '@angular/core';
import { TokenStorageService } from './_services/token-storage.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent implements OnInit {
  title(title: any) {
    throw new Error('Method not implemented.');
  }
  private roles: string[] = [];
  isLoggedIn = false;
  showAdminBoard = false;
  showModeratorBoard = false;
  username?: string;

  constructor(private tokenStorageService: TokenStorageService) { }

  ngOnInit(): void {
    this.isLoggedIn = !!this.tokenStorageService.getToken();

    if (this.isLoggedIn) {
      const user = this.tokenStorageService.getUser();
      this.roles = user.roles;

      this.showAdminBoard = this.roles.includes('ROLE_ADMIN');
      this.showModeratorBoard = this.roles.includes('ROLE_MODERATOR');

      this.username = user.username;
    }
  }

  logout(): void {
    this.tokenStorageService.signOut();
    window.location.reload();
  }
}

<div id="app">
  <nav class="navbar navbar-expand fixed-top navbar-dark bg-dark">
    <a href="#" class="navbar-brand">Helping Families Nelson</a>
    <ul class="navbar-nav mr-auto" routerLinkActive="active">
      <li class="nav-item">
        <a href="/home" class="nav-link" routerLink="home">Home </a>
      </li>
      <li class="nav-item">
        <li class="nav-item">
          <a href="/about" class="nav-link" routerLink="about">About </a>
        </li>
        <li class="nav-item">
          <li class="nav-item">
            <a href="/contact" class="nav-link" routerLink="contact">Contact </a>
          </li>
          <li class="nav-item">
        <a href="/donate" class="nav-link" routerLink="donate">Donate </a>
      </li>
      <!-- <li class="nav-item" *ngIf="showAdminBoard">
        <a href="/admin" class="nav-link" routerLink="admin">Admin Board</a>
      </li>
      <li class="nav-item" *ngIf="showModeratorBoard">
        <a href="/mod" class="nav-link" routerLink="mod">Moderator Board</a>
      </li>
      <li class="nav-item">
        <a href="/user" class="nav-link" *ngIf="isLoggedIn" routerLink="user">User</a>
      </li> -->
    </ul>

    <ul class="navbar-nav ml-auto" *ngIf="!isLoggedIn">
      <li class="nav-item">
        <a href="/register" class="nav-link" routerLink="register">Sign Up</a>
      </li>
      <li class="nav-item">
        <a href="/login" class="nav-link" routerLink="login">Login</a>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto" *ngIf="isLoggedIn">
      <li class="nav-item">
        <a href="/profile" class="nav-link" routerLink="profile">{{ username }}</a>
      </li>
      <li class="nav-item">
        <a href="/donate" class="nav-link" routerLink="donate">Donate </a>
      </li>
      <li class="nav-item">
        <a href class="nav-link" (click)="logout()">LogOut</a>
      </li>
    </ul>
  </nav>

  <div class="container" style="margin-top: 50px;">
    <router-outlet></router-outlet>
  </div>

  <app-footer></app-footer>
</div>
