// HelpingFamilesNelson-Angular/frontend/src/app/modules/carousel/carousel.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-carousel',
  templateUrl: './carousel.component.html',
  styleUrls: ['./carousel.component.css']
})
export class CarouselComponent implements OnInit {
 constructor() { }

  ngOnInit(): void {
  }

}

<!-- only generates if images are found -->
<ngb-carousel *ngIf="images">
    <ng-template ngbSlide>
      <div class="picsum-img-wrapper">
        <img src="..\..\..\..\public\images\cropped-HFN-Clothes.jpg" alt="Random first slide">
      </div>
      <div class="carousel-caption">
        <h3>Our Motto</h3>
        <p>Helping families with necessities to help children thrive and reach their potential</p>
      </div>
    </ng-template>
    <ng-template ngbSlide>
      <div class="picsum-img-wrapper">
        <img src="..\..\..\..\public\images\cropped-HFN-Clothes.jpg" alt="Random second slide">
      </div>
      <div class="carousel-caption">
        <h3>Our work</h3>
        <p>We facilitate donations from the community and the distribution of donated items to anyone who needs it</p>
      </div>
    </ng-template>
    <ng-template ngbSlide>
      <div class="picsum-img-wrapper">
        <img src="..\..\..\..\public\images\cropped-HFN-Clothes.jpg" alt="Random third slide">
      </div>
      <div class="carousel-caption">
        <h3>Good in the Hood</h3>
        <p>Thank you to everyone who voted for us and to Z Energy for their funding of this award</p>
      </div>
    </ng-template>
  </ngb-carousel>

// HelpingFamiliesNelson-Vue/frontend/src/components/models/Carousel.vue
<template>
    <div class="carousel">
        <MDBCarousel
            v-model="carousel1"
            :items="items1"
            :class="carousel"
            fade
            navColor="secondary"
        />
    </div>
</template>

<script>
  import { ref } from "vue";
  import { MDBCarousel } from "mdb-vue-ui-kit";

export default { 
    components: {
        MDBCarousel
    },
    setup() {
      const items1 = [
        {
          src: "/resized/simon-rae-jJYlr6H1ClM-unsplash-scaled.jpg",
          alt: "Our Motto",
          label: "Our Motto",
          caption: "Helping families with necessities to help children thrive and reach their potential",
        },
        {
          src: "/resized/HFN-Packs.jpeg",
          alt: "Our work",
          label: "Our work",
          caption: "We facilitate donations from the community and the distribution of donated items to anyone who needs it"
        },
        {
          src: "/resized/cropped-HFN-Fundraiser.jpeg",
          alt: "...",
          label: "Good in the Hood",
          caption:
            "Thank you to everyone who voted for us and to Z Energy for their funding of this award"
        }
      ];
      const carousel1 = ref(0);

      return {
        items1,
        carousel1
      };
    }
  };
</script>
<style scoped>
</style>
